### ISSUE TITLE
Package version is not compatible with laravel 5.5

### ISSUE THREAD

**Issue by Jnesselr** [stechstudio/laravel-vfs-adapter#1]
The package version is pretty strict, specifying only 5.4.x. This is causing me to be unable to update to laravel 5.5. Is it possible to restrict it to 5.x instead? Or are there known issues with 5.1-5.3?

**Comment by bubba-h57** [comment]
There are issues with earlier versions. But will get it updated to 5.5 as well.

**Comment by bubba-h57** [comment]
Version 2.0.0 released
