### ISSUE TITLE
[FR] Compatibility with Statamic 2 (Laravel 5.1)

### ISSUE THREAD

**Issue by RafaelKr** [stechstudio/laravel-vfs-adapter#7]
Hi, I'm using Statamic 2 and want to use this package with it.

I already created a fork and relaxed the illuminate/support version from `^5.5 | ^6.0` to `^5.1 || ^6.0`.  
Also note that I replaced the one pipe (`|`) with two pipes, as this is the correct form.

I'm using this actively for my test environment and it's working fine.  
Is there any reason it's starting at 5.5?

**Comment by RafaelKr** [comment]
I created a PR: https://github.com/stechstudio/laravel-vfs-adapter/pull/8
BTW: Thank you for that awesome package!

**Comment by RafaelKr** [comment]
I've just found this comment: https://github.com/stechstudio/laravel-vfs-adapter/issues/1#issuecomment-328624126

I've ran into no issues with Laravel 5.1, can you recall what these issues were?

**Comment by bubba-h57** [comment]
I do not, I do recall that I did indeed run into issues, but it was such a while back.
